apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploymentName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.deploymentName }}
  template:
    metadata:
      labels:
        app: {{ .Values.deploymentName }}
    spec:
{{ include "app-chart.initContainer" . | indent 6 }}
      containers:
      - name: demo-app-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8080
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
{{ include "app-chart.readinessProbe" . | indent 8 }}
{{ include "app-chart.livenessProbe" . | indent 8 }}